const util = require('util');
const fs = require('fs');
const exec = util.promisify(require('child_process').exec);
const stats = require("stats-lite")

const programs = [
  "cbench-automotive-bitcount",
  "cbench-automotive-qsort1", 
  "cbench-automotive-susan", 
  "cbench-bzip2",
  "cbench-consumer-jpeg-c",
  "cbench-consumer-jpeg-d",  
  "cbench-consumer-tiff2bw",
  "cbench-consumer-tiff2dither",
  "cbench-consumer-tiff2median",
  "cbench-consumer-tiff2rgba",
  "cbench-network-dijkstra",
  "cbench-network-patricia", 
  "cbench-office-stringsearch2",
  "cbench-security-rijndael",
  "cbench-security-sha",
  "cbench-telecom-adpcm-c",
  "cbench-telecom-adpcm-d",
  "cbench-telecom-crc32",
  "cbench-telecom-gsm",
  "polybench-cpu-3mm",
  "polybench-cpu-trmm",
  "polybench-cpu-lu",
  "polybench-cpu-doitgen",
  "polybench-cpu-jacobi-2d-imper",
  "polybench-cpu-fdtd-2d",
  "polybench-cpu-symm",
  "polybench-cpu-atax",
  "polybench-cpu-durbin",
  "polybench-cpu-bicg",
  "polybench-cpu-adi",
  "polybench-cpu-gemm",
  "polybench-cpu-jacobi-1d-imper",
  "polybench-cpu-gramschmidt",
  "polybench-cpu-fdtd-apml",
  "polybench-cpu-ludcmp",
  "polybench-cpu-trisolv",
  "polybench-cpu-gesummv",
  "polybench-cpu-mvt", 
  "polybench-cpu-syr2k",
  "polybench-cpu-cholesky",
  "polybench-cpu-dynprog",
  "polybench-cpu-medley-reg-detect",
  "polybench-cpu-medley-floyd-warshall",
  "polybench-cpu-syrk",
  "polybench-cpu-2mm",
  "polybench-cpu-seidel-2d",
  "polybench-cpu-gemver",  
  "asci_purple",
  "asc_sequoia_amgmk",
  "asc_sequoia_crystalmk",
  "asc_sequoia_irsmk", 
  "bitbench-drop3",
  "bitbench-five11",
  "bitbench-uudecode",
  "bitbench-uuencode",
  "coyote-alma",
  "coyote-huff",
  "coyote-lp",
  "csmith-ackies",
  "csmith-adams",
  "csmith-affagato",
  "csmith-ahmad",
  "csmith-akin",
  "csmith-albertson",
  "csmith-alcorn",
  "csmith-alexander",
  "csmith-alford",
  "csmith-allen",
  "csmith-alvarado",
  "csmith-amado",
  "csmith-ambrose",
  "csmith-anders",
  "csmith-anderson",
  "csmith-andrada",
  "csmith-anguiano",
  "csmith-ansley",
  "csmith-ardis",
  "csmith-arends",
  "csmith-armitage",
  "csmith-armstead",
  "csmith-arnold",
  "csmith-ash",
  "csmith-atchison",
  "csmith-athearn",
  "csmith-athey",
  "csmith-atkeson",
  "csmith-atkinson",
  "csmith-babel",
  "csmith-bacher",
  "csmith-bacich",
  "csmith-backes",
  "csmith-baggett",
  "csmith-bailey",
  "csmith-baird",
  "csmith-baker",
  "csmith-balderas",
  "csmith-balkcom",
  "csmith-balke",
  "csmith-ballard",
  "csmith-balmos",
  "csmith-banks",
  "csmith-baptiste",
  "csmith-barajas",
  "csmith-baranowski",
  "csmith-barbour",
  "csmith-barnes",
  "csmith-barnett",
  "csmith-barrett",
  "csmith-barrios",
  "csmith-barrocas",
  "csmith-barrow",
  "csmith-barton",
  "csmith-bates",
  "csmith-battle",
  "csmith-batun",
  "csmith-baver",
  "csmith-beaman",
  "csmith-beckman",
  "csmith-becnel",
  "csmith-becwar",
  "csmith-behan",
  "csmith-behm",
  "csmith-belanger",
  "csmith-bendel",
  "csmith-bennett",
  "csmith-bentley",
  "csmith-bequette",
  "csmith-berger",
  "csmith-bertolami",
  "csmith-bettendorf",
  "csmith-betzer",
  "csmith-bevington",
  "csmith-beyer",
  "csmith-bierlein",
  "csmith-biggs",
  "csmith-biglin",
  "csmith-billington",
  "csmith-billiter",
  "csmith-bingham",
  "csmith-black",
  "csmith-blackerby",
  "csmith-blair",
  "csmith-bledsoe",
  "csmith-blount",
  "csmith-blue",
  "csmith-bodi",
  "csmith-boland",
  "csmith-booker",
  "csmith-booth",
  "csmith-bordner",
  "csmith-botelho",
  "csmith-botello",
  "csmith-bourgeois",
  "csmith-bowman",
  "csmith-boyer",
  "csmith-boyle",
  "csmith-brackeen",
  "csmith-bradford",
  "csmith-braun",
  "csmith-brechbiel",
  "csmith-brewster",
  "csmith-brightharp",
  "csmith-brimer",
  "csmith-brito",
  "csmith-britt",
  "csmith-broadnax",
  "csmith-browne",
  "csmith-bruce",
  "csmith-brumfield",
  "csmith-bryant",
  "csmith-bublitz",
  "csmith-buchanan",
  "csmith-buckner",
  "csmith-bullock",
  "csmith-burch",
  "csmith-burgess",
  "csmith-burke",
  "csmith-burkhart",
  "csmith-burns",
  "csmith-burroughs",
  "csmith-burrus",
  "csmith-burton",
  "csmith-busch",
  "csmith-bustamente",
  "csmith-bustos",
  "csmith-butcher",
  "csmith-butler",
  "csmith-byrd",
  "csmith-cain",
  "csmith-caldwell",
  "csmith-caligiuri",
  "csmith-calles",
  "csmith-cameron",
  "csmith-campbell",
  "csmith-campos",
  "csmith-cannon",
  "csmith-cantu",
  "csmith-carnahan",
  "csmith-carol",
  "csmith-carr",
  "csmith-carrico",
  "csmith-carson",
  "csmith-carter",
  "csmith-cartwright",
  "csmith-carvalho",
  "csmith-casey",
  "csmith-cash",
  "csmith-castillo",
  "csmith-castorena",
  "csmith-castro",
  "csmith-cathcart",
  "csmith-causey",
  "csmith-cervantes",
  "csmith-chambers",
  "csmith-chang",
  "csmith-chase",
  "csmith-chatman",
  "csmith-chauvin",
  "csmith-chavez",
  "csmith-chenault",
  "csmith-cheshire",
  "csmith-chicas",
  "csmith-childers",
  "csmith-christensen",
  "csmith-christofferso",
  "csmith-claar",
  "csmith-clark",
  "csmith-claybrook",
  "csmith-cleaver",
  "csmith-clinard",
  "csmith-cline",
  "csmith-coats",
  "csmith-cobb",
  "csmith-coe",
  "csmith-cohen",
  "csmith-colella",
  "csmith-coleman",
  "csmith-coll",
  "csmith-collins",
  "csmith-colon",
  "csmith-combs",
  "csmith-conner",
  "csmith-contreras",
  "csmith-cook",
  "csmith-cooper",
  "csmith-correa",
  "csmith-costales",
  "csmith-cox",
  "csmith-crafton",
  "csmith-craig",
  "csmith-crawford",
  "csmith-creamer",
  "csmith-creekmur",
  "csmith-crespo",
  "csmith-crock",
  "csmith-crossmon",
  "csmith-crosson",
  "csmith-crouchet",
  "csmith-crowe",
  "csmith-crutcher",
  "csmith-cruz",
  "csmith-culp",
  "csmith-cunningham",
  "csmith-curtis",
  "csmith-cuthbertson",
  "csmith-cygan",
  "csmith-daddio",
  "csmith-daking",
  "csmith-danforth",
  "csmith-daniels",
  "csmith-darnell",
  "csmith-davidson",
  "csmith-davis",
  "csmith-day",
  "csmith-deal",
  "csmith-deer",
  "csmith-dehart",
  "csmith-deldonno",
  "csmith-delgadillo",
  "csmith-demars",
  "csmith-demers",
  "csmith-demeter",
  "csmith-demps",
  "csmith-denby",
  "csmith-dennis",
  "csmith-derks",
  "csmith-deshong",
  "csmith-dieppa",
  "csmith-difonzo",
  "csmith-digiovanni",
  "csmith-ditch",
  "csmith-divine",
  "csmith-dixon",
  "csmith-dodimead",
  "csmith-donaldson",
  "csmith-donnerberg",
  "csmith-dorrance",
  "csmith-dossey",
  "csmith-draggoo",
  "csmith-dray",
  "csmith-dubie",
  "csmith-dudenhoeffer",
  "csmith-duncan",
  "csmith-dunnings",
  "csmith-durfee",
  "csmith-dvorak",
  "csmith-dwyer",
  "csmith-dykas",
  "csmith-eads",
  "csmith-earl",
  "csmith-easterling",
  "csmith-eberle",
  "csmith-eddy",
  "csmith-edgar",
  "csmith-egersdorf",
  "csmith-ekberg",
  "csmith-ekstrom",
  "csmith-elderidge",
  "csmith-elkins",
  "csmith-elliott",
  "csmith-elmore",
  "csmith-elrod",
  "csmith-encarnacion",
  "csmith-engleberg",
  "csmith-enoch",
  "csmith-escovedo",
  "csmith-esmond",
  "csmith-espinoza",
  "csmith-essig",
  "csmith-evans",
  "csmith-everett",
  "csmith-fairchild",
  "csmith-falls",
  "csmith-faltus",
  "csmith-faulds",
  "csmith-faust",
  "csmith-faz",
  "csmith-feder",
  "csmith-felton",
  "csmith-ferdinand",
  "csmith-ferguson",
  "csmith-ferkovich",
  "csmith-fernandez",
  "csmith-fichter",
  "csmith-fields",
  "csmith-fierro",
  "csmith-filip",
  "csmith-finch",
  "csmith-finger",
  "csmith-fischer",
  "csmith-fisher",
  "csmith-flagg",
  "csmith-flanders",
  "csmith-fleniken",
  "csmith-fletcher",
  "csmith-flores",
  "csmith-floyd",
  "csmith-fontenot",
  "csmith-foor",
  "csmith-forbis",
  "csmith-foss",
  "csmith-foster",
  "csmith-fouts",
  "csmith-fox",
  "csmith-francis",
  "csmith-frank",
  "csmith-franklin",
  "csmith-frantz",
  "csmith-freeman",
  "csmith-french",
  "csmith-frost",
  "csmith-fuller",
  "csmith-fung",
  "csmith-funk",
  "csmith-gaddy",
  "csmith-gainer",
  "csmith-gaither",
  "csmith-galan",
  "csmith-galbraith",
  "csmith-galloway",
  "csmith-gambone",
  "csmith-garay",
  "csmith-garcia",
  "csmith-garner",
  "csmith-garrison",
  "csmith-garrity",
  "csmith-gaskin",
  "csmith-gaylord",
  "csmith-geist",
  "csmith-geter",
  "csmith-gibson",
  "csmith-giebler",
  "csmith-gilbert",
  "csmith-gill",
  "csmith-gilliss",
  "csmith-gionet",
  "csmith-githens",
  "csmith-glenn",
  "csmith-glomb",
  "csmith-godwin",
  "csmith-goers",
  "csmith-goguen",
  "csmith-gold",
  "csmith-goldbach",
  "csmith-gomez",
  "csmith-gonsalves",
  "csmith-gonzales",
  "csmith-gonzalez",
  "csmith-goodwin",
  "csmith-gooslin",
  "csmith-gordon",
  "csmith-goslee",
  "csmith-gough",
  "csmith-goulet",
  "csmith-gowans",
  "csmith-green",
  "csmith-greene",
  "csmith-greigo",
  "csmith-gresham",
  "csmith-grimes",
  "csmith-grimsley",
  "csmith-grissom",
  "csmith-grossen",
  "csmith-gruber",
  "csmith-guillory",
  "csmith-gunn",
  "csmith-guthrie",
  "csmith-gutierrez",
  "csmith-gutshall",
  "csmith-guy",
  "csmith-hacher",
  "csmith-hackathorn",
  "csmith-hageman",
  "csmith-hagen",
  "csmith-haight",
  "csmith-haines",
  "csmith-hall",
  "csmith-hamilton",
  "csmith-hamlin",
  "csmith-hammett",
  "csmith-hanks",
  "csmith-hansen",
  "csmith-harder",
  "csmith-hardin",
  "csmith-harding",
  "csmith-hare",
  "csmith-harper",
  "csmith-harris",
  "csmith-hartage",
  "csmith-hartman",
  "csmith-harty",
  "csmith-hasselman",
  "csmith-hastings",
  "csmith-havlik",
  "csmith-hayes",
  "csmith-haymond",
  "csmith-haynes",
  "csmith-hays",
  "csmith-haywood",
  "csmith-heaberlin",
  "csmith-head",
  "csmith-hedges",
  "csmith-hedgespeth",
  "csmith-heiman",
  "csmith-helmick",
  "csmith-henderson",
  "csmith-hendricks",
  "csmith-hennings",
  "csmith-henry",
  "csmith-hernandez",
  "csmith-herrera",
  "csmith-hester",
  "csmith-hicks",
  "csmith-highland",
  "csmith-hightower",
  "csmith-hill",
  "csmith-hinojos",
  "csmith-hinz",
  "csmith-hirota",
  "csmith-hite",
  "csmith-hittle",
  "csmith-hobbs",
  "csmith-hodgkins",
  "csmith-hoekstra",
  "csmith-holden",
  "csmith-holladay",
  "csmith-holland",
  "csmith-hollister",
  "csmith-holmes",
  "csmith-honaker",
  "csmith-hooper",
  "csmith-hopkins",
  "csmith-hopping",
  "csmith-horney",
  "csmith-horrigan",
  "csmith-horwath",
  "csmith-houston",
  "csmith-howard",
  "csmith-hoy",
  "csmith-hoyle",
  "csmith-hubbard",
  "csmith-huff",
  "csmith-hughes",
  "csmith-hulsey",
  "csmith-humphrey",
  "csmith-hunter",
  "csmith-hwang",
  "csmith-irland",
  "csmith-isbrecht",
  "csmith-israels",
  "csmith-ivory",
  "csmith-ivy",
  "csmith-jackson",
  "csmith-jacob",
  "csmith-jacobs",
  "csmith-jaimes",
  "csmith-james",
  "csmith-jaques",
  "csmith-jaramillo",
  "csmith-jenkins",
  "csmith-jensen",
  "csmith-jimenez",
  "csmith-johnson",
  "csmith-johnston",
  "csmith-jonas",
  "csmith-jones",
  "csmith-jordan",
  "csmith-joseph",
  "csmith-jovich",
  "csmith-juel",
  "csmith-juran",
  "csmith-kabat",
  "csmith-kammerer",
  "csmith-kaster",
  "csmith-kauffman",
  "csmith-keller",
  "csmith-kelly",
  "csmith-kelsey",
  "csmith-kemp",
  "csmith-kern",
  "csmith-ketterling",
  "csmith-killian",
  "csmith-kim",
  "csmith-king",
  "csmith-kingsley",
  "csmith-kinkel",
  "csmith-kirkham",
  "csmith-kiser",
  "csmith-kline",
  "csmith-knight",
  "csmith-kodadek",
  "csmith-komar",
  "csmith-korczynski",
  "csmith-kral",
  "csmith-kruger",
  "csmith-kujawski",
  "csmith-kunzel",
  "csmith-kwan",
  "csmith-lachley",
  "csmith-lamper",
  "csmith-lampley",
  "csmith-lane",
  "csmith-lang",
  "csmith-lanning",
  "csmith-larrison",
  "csmith-larsen",
  "csmith-laundree",
  "csmith-lebrecque",
  "csmith-lederman",
  "csmith-lee",
  "csmith-lefort",
  "csmith-lehmann",
  "csmith-lemm",
  "csmith-lemon",
  "csmith-lendon",
  "csmith-leneave",
  "csmith-leon",
  "csmith-levine",
  "csmith-lewis",
  "csmith-liberty",
  "csmith-lieber",
  "csmith-limon",
  "csmith-lincourt",
  "csmith-linden",
  "csmith-lites",
  "csmith-livezey",
  "csmith-longo",
  "csmith-lopez",
  "csmith-lovejoy",
  "csmith-lowry",
  "csmith-lunford",
  "csmith-luongo",
  "csmith-lusk",
  "csmith-macdonald",
  "csmith-mackay",
  "csmith-macklin",
  "csmith-macvane",
  "csmith-madison",
  "csmith-maggard",
  "csmith-major",
  "csmith-mandolini",
  "csmith-manley",
  "csmith-mannino",
  "csmith-marc",
  "csmith-markarian",
  "csmith-markham",
  "csmith-markus",
  "csmith-marshall",
  "csmith-martinez",
  "csmith-mason",
  "csmith-massiah",
  "csmith-mastroianni",
  "csmith-mathis",
  "csmith-mattie",
  "csmith-mattos",
  "csmith-mattox",
  "csmith-mayoras",
  "csmith-mazzola",
  "csmith-mcalister",
  "csmith-mcbride",
  "csmith-mccants",
  "csmith-mccarroll",
  "csmith-mccarter",
  "csmith-mcchristian",
  "csmith-mcclary",
  "csmith-mcclurg",
  "csmith-mccoy",
  "csmith-mccurry",
  "csmith-mcdill",
  "csmith-mcdonald",
  "csmith-mcdougal",
  "csmith-mcelrath",
  "csmith-mcfarlane",
  "csmith-mcgarey",
  "csmith-mcgraw",
  "csmith-mckay",
  "csmith-mckenzie",
  "csmith-mckoan",
  "csmith-mclarney",
  "csmith-mclaughlin",
  "csmith-mclaurin",
  "csmith-mclean",
  "csmith-mclellan",
  "csmith-mcleod",
  "csmith-mcmahon",
  "csmith-mcmurray",
  "csmith-mcrae",
  "csmith-mcwhorter",
  "csmith-meade",
  "csmith-meadows",
  "csmith-medders",
  "csmith-medina",
  "csmith-melody",
  "csmith-melton",
  "csmith-melvin",
  "csmith-mendez",
  "csmith-menendez",
  "csmith-menke",
  "csmith-merchant",
  "csmith-merritt",
  "csmith-mestad",
  "csmith-meyers",
  "csmith-mickle",
  "csmith-middaugh",
  "csmith-miller",
  "csmith-milton",
  "csmith-ming",
  "csmith-mitchell",
  "csmith-monopoli",
  "csmith-mooneyham",
  "csmith-moore",
  "csmith-moralez",
  "csmith-moran",
  "csmith-morey",
  "csmith-morin",
  "csmith-moris",
  "csmith-morrell",
  "csmith-morrical",
  "csmith-morris",
  "csmith-morrison",
  "csmith-mortimer",
  "csmith-moskowitz",
  "csmith-moua",
  "csmith-mueller",
  "csmith-muller",
  "csmith-mullins",
  "csmith-mulvaney",
  "csmith-munger",
  "csmith-muni",
  "csmith-munoz",
  "csmith-murawski",
  "csmith-murphy",
  "csmith-murray",
  "csmith-nadal",
  "csmith-nakamura",
  "csmith-nall",
  "csmith-navarrete",
  "csmith-naylor",
  "csmith-neal",
  "csmith-negron",
  "csmith-nelson",
  "csmith-nesmith",
  "csmith-newman",
  "csmith-newton",
  "csmith-nguyen",
  "csmith-nicholas",
  "csmith-nicholson",
  "csmith-nickels",
  "csmith-numbers",
  "csmith-nunn",
  "csmith-obrien",
  "csmith-obyrne",
  "csmith-ochoa",
  "csmith-oconnell",
  "csmith-oconnor",
  "csmith-ogg",
  "csmith-ohmen",
  "csmith-olson",
  "csmith-oneal",
  "csmith-oneil",
  "csmith-ortiz",
  "csmith-osgood",
  "csmith-otto",
  "csmith-ownby",
  "csmith-pagani",
  "csmith-palazzola",
  "csmith-parke",
  "csmith-parnell",
  "csmith-passe",
  "csmith-patel",
  "csmith-patrick",
  "csmith-paxson",
  "csmith-payne",
  "csmith-pearl",
  "csmith-pearson",
  "csmith-pease",
  "csmith-peatross",
  "csmith-pedlow",
  "csmith-pedroza",
  "csmith-pefferkorn",
  "csmith-peiper",
  "csmith-pelayo",
  "csmith-pelosi",
  "csmith-pena",
  "csmith-pendergrass",
  "csmith-peoples",
  "csmith-pepin",
  "csmith-perez",
  "csmith-perng",
  "csmith-perrien",
  "csmith-perry",
  "csmith-peters",
  "csmith-peterson",
  "csmith-petter",
  "csmith-phelps",
  "csmith-phillips",
  "csmith-phipps",
  "csmith-piccolomini",
  "csmith-pierce",
  "csmith-pinc",
  "csmith-pinto",
  "csmith-pittman",
  "csmith-pitts",
  "csmith-pixley",
  "csmith-plateroti",
  "csmith-pogue",
  "csmith-poissant",
  "csmith-polin",
  "csmith-pollock",
  "csmith-poole",
  "csmith-poteet",
  "csmith-potocki",
  "csmith-potter",
  "csmith-pousson",
  "csmith-powell",
  "csmith-prater",
  "csmith-preston",
  "csmith-prewitt",
  "csmith-prickett",
  "csmith-priestley",
  "csmith-propheter",
  "csmith-propst",
  "csmith-puckett",
  "csmith-ragasa",
  "csmith-ramirez",
  "csmith-ramsey",
  "csmith-rapelyea",
  "csmith-rathbone",
  "csmith-rayl",
  "csmith-reale",
  "csmith-reardon",
  "csmith-reaume",
  "csmith-rebuck",
  "csmith-rebuldela",
  "csmith-red",
  "csmith-reece",
  "csmith-reed",
  "csmith-reevers",
  "csmith-reff",
  "csmith-rehling",
  "csmith-reid",
  "csmith-renner",
  "csmith-renteria",
  "csmith-resendez",
  "csmith-resnick",
  "csmith-respess",
  "csmith-reyna",
  "csmith-rhoades",
  "csmith-rhodes",
  "csmith-rice",
  "csmith-richardson",
  "csmith-ricketts",
  "csmith-rider",
  "csmith-riggins",
  "csmith-rinehart",
  "csmith-rivera",
  "csmith-roan",
  "csmith-roberts",
  "csmith-robertson",
  "csmith-robinette",
  "csmith-robinson",
  "csmith-robledo",
  "csmith-rocha",
  "csmith-rodas",
  "csmith-rodriguez",
  "csmith-rodriquez",
  "csmith-rogers",
  "csmith-rokus",
  "csmith-rollinger",
  "csmith-roman",
  "csmith-roose",
  "csmith-rosario",
  "csmith-rose",
  "csmith-ross",
  "csmith-rossman",
  "csmith-rothfeld",
  "csmith-roudebush",
  "csmith-rowland",
  "csmith-roy",
  "csmith-rubinson",
  "csmith-rubio",
  "csmith-rucker",
  "csmith-ruiz",
  "csmith-russell",
  "csmith-rutledge",
  "csmith-saiz",
  "csmith-salinas",
  "csmith-salmi",
  "csmith-samuels",
  "csmith-sanchez",
  "csmith-sanders",
  "csmith-sanderson",
  "csmith-sandy",
  "csmith-santiago",
  "csmith-saunders",
  "csmith-schade",
  "csmith-scheer",
  "csmith-schilling",
  "csmith-schlau",
  "csmith-schmidt",
  "csmith-schmitmeyer",
  "csmith-schmitz",
  "csmith-schneider",
  "csmith-schrimsher",
  "csmith-schuster",
  "csmith-scott",
  "csmith-segal",
  "csmith-sellers",
  "csmith-seltzer",
  "csmith-serrano",
  "csmith-session",
  "csmith-sevy",
  "csmith-shabel",
  "csmith-shadle",
  "csmith-shaefer",
  "csmith-shah",
  "csmith-shamp",
  "csmith-sharpe",
  "csmith-sheline",
  "csmith-shelton",
  "csmith-shepherd",
  "csmith-sheppard",
  "csmith-sherbert",
  "csmith-shinn",
  "csmith-shively",
  "csmith-shoop",
  "csmith-sideris",
  "csmith-siefkes",
  "csmith-simmons",
  "csmith-simpson",
  "csmith-sims",
  "csmith-sinclair",
  "csmith-singer",
  "csmith-slack",
  "csmith-slayton",
  "csmith-sloan",
  "csmith-smallwood",
  "csmith-smith",
  "csmith-soders",
  "csmith-soehl",
  "csmith-sommers",
  "csmith-sorensen",
  "csmith-sotomayor",
  "csmith-souliere",
  "csmith-sowell",
  "csmith-spaniel",
  "csmith-sparks",
  "csmith-spera",
  "csmith-spicer",
  "csmith-spivey",
  "csmith-sprouse",
  "csmith-stackhouse",
  "csmith-stade",
  "csmith-stahl",
  "csmith-staley",
  "csmith-stallard",
  "csmith-stancill",
  "csmith-starr",
  "csmith-stavrositu",
  "csmith-steele",
  "csmith-stevens",
  "csmith-stevenson",
  "csmith-stewart",
  "csmith-stogsdill",
  "csmith-stoneback",
  "csmith-stonge",
  "csmith-strange",
  "csmith-street",
  "csmith-strickland",
  "csmith-striegel",
  "csmith-strubbe",
  "csmith-stubblefield",
  "csmith-stucker",
  "csmith-sturmer",
  "csmith-suggett",
  "csmith-sullivan",
  "csmith-surratt",
  "csmith-susko",
  "csmith-sykes",
  "csmith-sykora",
  "csmith-tackett",
  "csmith-tacy",
  "csmith-tangerman",
  "csmith-tart",
  "csmith-tarter",
  "csmith-taylor",
  "csmith-terrell",
  "csmith-terry",
  "csmith-tharp",
  "csmith-thero",
  "csmith-therrien",
  "csmith-theus",
  "csmith-thigpen",
  "csmith-thomas",
  "csmith-thompson",
  "csmith-thong",
  "csmith-thornhill",
  "csmith-thurman",
  "csmith-tillery",
  "csmith-tompkins",
  "csmith-toppin",
  "csmith-torbus",
  "csmith-torres",
  "csmith-toussaint",
  "csmith-townsend",
  "csmith-tracy",
  "csmith-tran",
  "csmith-treadway",
  "csmith-treece",
  "csmith-trilli",
  "csmith-trinkle",
  "csmith-truitt",
  "csmith-turner",
  "csmith-ullmann",
  "csmith-urie",
  "csmith-vacheresse",
  "csmith-valdez",
  "csmith-valentine",
  "csmith-vanwinkle",
  "csmith-vasquez",
  "csmith-vaughn",
  "csmith-vayner",
  "csmith-vazquez",
  "csmith-vega",
  "csmith-veliz",
  "csmith-villalva",
  "csmith-villanueva",
  "csmith-visser",
  "csmith-waddell",
  "csmith-wadding",
  "csmith-wagner",
  "csmith-wahlen",
  "csmith-waldrop",
  "csmith-walker",
  "csmith-wallace",
  "csmith-wang",
  "csmith-warburton",
  "csmith-ward",
  "csmith-warren",
  "csmith-warrington",
  "csmith-washington",
  "csmith-waters",
  "csmith-watkins",
  "csmith-watson",
  "csmith-wearing",
  "csmith-weaver",
  "csmith-weinberger",
  "csmith-weir",
  "csmith-welch",
  "csmith-wells",
  "csmith-welsh",
  "csmith-wemmer",
  "csmith-wesley",
  "csmith-west",
  "csmith-westmark",
  "csmith-westmoreland",
  "csmith-wheeler",
  "csmith-whitaker",
  "csmith-white",
  "csmith-whitfield",
  "csmith-whitt",
  "csmith-whitworth",
  "csmith-widell",
  "csmith-wiedmann",
  "csmith-wiens",
  "csmith-wietzel",
  "csmith-wilbert",
  "csmith-wilcox",
  "csmith-wilkerson",
  "csmith-wilkins",
  "csmith-wilkowitz",
  "csmith-wilks",
  "csmith-williams",
  "csmith-williamson",
  "csmith-wills",
  "csmith-wilson",
  "csmith-wiren",
  "csmith-witt",
  "csmith-wolff",
  "csmith-wolpert",
  "csmith-wolsted",
  "csmith-wood",
  "csmith-woods",
  "csmith-worth",
  "csmith-wright",
  "csmith-wu",
  "csmith-wyatt",
  "csmith-wynia",
  "csmith-yager",
  "csmith-yaney",
  "csmith-yepez",
  "csmith-york",
  "csmith-young",
  "csmith-zaldana",
  "csmith-zanella",
  "csmith-zarate",
  "csmith-zeller",
  "csmith-zepeda",
  "dhrystone-dry",
  "dhrystone-fldry",
  "doe_proxyapps_miniamr",
  "doe_proxyapps_minigmg",
  "doe_proxyapps_pathfinder",
  "doe_proxyapps_rsbench",
  "doe_proxyapps_simple_moc",
  "doe_proxyapps_xsbench",
  "fhourstones",
  "fhourstones_31",
  "freebench-analyzer",
  "freebench-distray",
  "freebench-fourinarow",
  "freebench-mason",
  "freebench-neural",
  "freebench-pcompress2",
  "freebench-pifft",
  "game-fannkuch",
  "game-n-body",
  "game-nsieve-bits",
  "game-partialsums",
  "game-puzzle",
  "game-recursive",
  "game-spectral-norm",
  "linpack",
  "llubenchmark",
  "mafft",
  "mallocbench-cfrac",
  "mccat-main",
  "mccat-bintr",
  "mccat-bisect",
  "mccat-eks",
  "mccat-qbsort",
  "mccat-iotest",
  "mccat-vor",
  "mccat-testtrie",
  "mccat-trie",
  "mcgill-chomp",
  "mcgill-queens",
  "mcgill-exptree",
  "mcgill-misr",
  "mediabench-g721-encode",
  "mediabench-adpcm-rawcaudio",
  "mediabench-gsm-toast",
  "mediabench-adpcm-rawdaudio",
  "mediabench-mpeg2-dec",
  "misc-oourafft",
  "misc-flops-6",
  "misc-mandel-2",
  "misc-evalloop",
  "misc-salsa20",
  "misc-fp-convert",
  "misc-whetstone",
  "misc-dt",
  "misc-flops-2",
  "misc-perlin",
  "misc-flops-3",
  "misc-himenobmtxpa",
  "misc-flops-1",
  "misc-flops",
  "misc-reed-solomon",
  "misc-mandel",
  "misc-flops-7",
  "misc-flops-4",
  "misc-matmul_f64_4x4",
  "misc-pi",
  "misc-fbench",
  "misc-flops-8",
  "misc-revert-bits",
  "misc-ffbench",
  "misc-lowercase",
  "misc-flops-5",
  "misc-richards",
  "nbench",
  "npb-serial-dc",
  "npb-serial-is",
  "olden-bh",
  "olden-bisort",
  "olden-em3d",
  "olden-health",
  "olden-mst",
  "olden-perimeter",
  "olden-power",
  "olden-treeadd",
  "olden-tsp",
  "olden-voronoi",
  "prolangs-agrep",
  "prolangs-allroots",
  "prolangs-archie-client",
  "prolangs-assembler",
  "prolangs-bison",
  "prolangs-cdecl",
  "prolangs-compiler",
  "prolangs-fixoutput",
  "prolangs-gnugo",
  "prolangs-loader",
  "prolangs-unix-smail",
  "ptrdist-anagram",
  "ptrdist-bc",
  "ptrdist-ft",
  "ptrdist-ks",
  "ptrdist-yacr2",
  "scimark2-c",
  "shootout-ackermann",
  "shootout-ary3",
  "shootout-fib2",
  "shootout-hash",
  "shootout-heapsort",
  "shootout-hello",
  "shootout-lists",
  "shootout-matrix",
  "shootout-methcall",
  "shootout-nestedloop",
  "shootout-objinst",
  "shootout-random",
  "shootout-sieve",
  "shootout-strcat",
  "sim",
  "stanford-bubblesort",
  "stanford-floatmm",
  "stanford-intmm",
  "stanford-oscar",
  "stanford-puzzle",
  "stanford-queens",
  "stanford-quicksort",
  "stanford-realmm",
  "stanford-towers",
  "stanford-treesort",
  "trimaran-enc3des",
  "trimaran-encmd5",
  "trimaran-encpc1",
  "trimaran-encrc4",
  "trimaran-netbenchcrc",
  "trimaran-netbenchurl",
  "tsvc-controlflow-dbl",
  "tsvc-controlflow-flt",
  "tsvc-controlloops-dbl",
  "tsvc-controlloops-flt",
  "tsvc-crossingthresholds-dbl",
  "tsvc-crossingthresholds-flt",
  "tsvc-equivalencing-dbl",
  "tsvc-equivalencing-flt",
  "tsvc-expansion-dbl",
  "tsvc-expansion-flt",
  "tsvc-globaldataflow-dbl",
  "tsvc-globaldataflow-flt",
  "tsvc-indirectadressing-dbl",
  "tsvc-indirectadressing-flt",
  "tsvc-inductionvariable-dbl",
  "tsvc-inductionvariable-flt",
  "tsvc-lineardependence-dbl",
  "tsvc-lineardependence-flt",
  "tsvc-looprerolling-dbl",
  "tsvc-looprerolling-flt",
  "tsvc-looprestructuring-dbl",
  "tsvc-looprestructuring-flt",
  "tsvc-nodesplitting-dbl",
  "tsvc-nodesplitting-flt",
  "tsvc-packing-dbl",
  "tsvc-packing-flt",
  "tsvc-recurrences-dbl",
  "tsvc-recurrences-flt",
  "tsvc-reductions-dbl",
  "tsvc-reductions-flt",
  "tsvc-searching-dbl",
  "tsvc-searching-flt",
  "tsvc-statementreordering-dbl",
  "tsvc-statementreordering-flt",
  "tsvc-symbolics-dbl",
  "tsvc-symbolics-flt",
  "versabench-8b10b",
  "versabench-beamformer",
  "versabench-bmm",
  "versabench-dbms",
  "versabench-ecbdes"
] 

const total_execution = 1;
const maxBuffer = Infinity;

const skip_calibration = true;

const datasets = [
  { program : "cbench-automotive-bitcount", value: "--dataset_uoa=number-0001", name: "dataset1"},
  { program : "cbench-automotive-bitcount", value: "--dataset_uoa=number-0002", name: "dataset2"},
  { program : "cbench-automotive-bitcount", value: "--dataset_uoa=number-0003", name: "dataset3"},
  { program : "cbench-automotive-bitcount", value: "--dataset_uoa=number-0004", name: "dataset4"},
  { program : "cbench-automotive-bitcount", value: "--dataset_uoa=number-0005", name: "dataset5"}, 

  { program : "cbench-automotive-qsort1", value: "--dataset_uoa=cdataset-qsort-0001", name: "dataset1"},
  { program : "cbench-automotive-qsort1", value: "--dataset_uoa=cdataset-qsort-0002", name: "dataset2"},
  { program : "cbench-automotive-qsort1", value: "--dataset_uoa=cdataset-qsort-0003", name: "dataset3"},
  { program : "cbench-automotive-qsort1", value: "--dataset_uoa=cdataset-qsort-0004", name: "dataset4"},
  { program : "cbench-automotive-qsort1", value: "--dataset_uoa=cdataset-qsort-0005", name: "dataset5"},

  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0001", name: "dataset1" , input: "edges"},
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0002", name: "dataset2", input: "edges"},
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0003", name: "dataset3" , input: "edges"},
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0004", name: "dataset4", input: "edges"},
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0005", name: "dataset5", input: "edges"},
  
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0001", name: "dataset1" , input: "corners"},
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0002", name: "dataset2", input: "corners"},
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0003", name: "dataset3" , input: "corners"},
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0004", name: "dataset4", input: "corners"},
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0005", name: "dataset5", input: "corners"},

  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0001", name: "dataset1" , input: "smoothing"},
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0002", name: "dataset2", input: "smoothing"},
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0003", name: "dataset3" , input: "smoothing"},
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0004", name: "dataset4", input: "smoothing"},
  { program : "cbench-automotive-susan", value: "--dataset_uoa=image-pgm-0005", name: "dataset5", input: "smoothing"},

  { program : "cbench-bzip2", value: "--dataset_uoa=bzip2-0001", name: "dataset1" , input: "decode"},
  { program : "cbench-bzip2", value: "--dataset_uoa=bzip2-0002", name: "dataset2" , input: "decode"},
  { program : "cbench-bzip2", value: "--dataset_uoa=bzip2-0003", name: "dataset3" , input: "decode"},
  { program : "cbench-bzip2", value: "--dataset_uoa=bzip2-0004", name: "dataset4" , input: "decode"},
  { program : "cbench-bzip2", value: "--dataset_uoa=bzip2-0005", name: "dataset5" , input: "decode"},

  { program : "cbench-bzip2", value: "--dataset_file=\"data.txt\" env.dataset_filename_1=data.txt --dataset_uoa=txt-0001", name: "dataset1" , input: "encode"},
  { program : "cbench-bzip2", value: "--dataset_file=\"data.txt\" env.dataset_filename_1=data.txt --dataset_uoa=txt-0002", name: "dataset2" , input: "encode"},
  { program : "cbench-bzip2", value: "--dataset_file=\"data.txt\" env.dataset_filename_1=data.txt --dataset_uoa=txt-0003", name: "dataset3" , input: "encode"},
  { program : "cbench-bzip2", value: "--dataset_file=\"data.txt\" env.dataset_filename_1=data.txt --dataset_uoa=txt-0004", name: "dataset4" , input: "encode"},
  { program : "cbench-bzip2", value: "--dataset_file=\"data.txt\" env.dataset_filename_1=data.txt --dataset_uoa=txt-0005", name: "dataset5" , input: "encode"}, 


  { program : "cbench-consumer-jpeg-c", value: "--dataset_uoa=image-ppm-0001", name: "dataset1"},
  { program : "cbench-consumer-jpeg-c", value: "--dataset_uoa=image-ppm-0002", name: "dataset2"},
  { program : "cbench-consumer-jpeg-c", value: "--dataset_uoa=image-ppm-0003", name: "dataset3"},
  { program : "cbench-consumer-jpeg-c", value: "--dataset_uoa=image-ppm-0004", name: "dataset4"},
  { program : "cbench-consumer-jpeg-c", value: "--dataset_uoa=image-ppm-0005", name: "dataset5"},

  { program : "cbench-consumer-jpeg-d", value: "--dataset_uoa=image-jpeg-0001", name: "dataset1"},
  { program : "cbench-consumer-jpeg-d", value: "--dataset_uoa=image-jpeg-0002", name: "dataset2"},
  { program : "cbench-consumer-jpeg-d", value: "--dataset_uoa=image-jpeg-0003", name: "dataset3"},
  { program : "cbench-consumer-jpeg-d", value: "--dataset_uoa=image-jpeg-0004", name: "dataset4"},
  { program : "cbench-consumer-jpeg-d", value: "--dataset_uoa=image-jpeg-0005", name: "dataset5"},

  { program : "cbench-consumer-tiff2bw", value: "--dataset_uoa=image-tiff-0001", name: "dataset1"},
  { program : "cbench-consumer-tiff2bw", value: "--dataset_uoa=image-tiff-0002", name: "dataset2"},
  { program : "cbench-consumer-tiff2bw", value: "--dataset_uoa=image-tiff-0003", name: "dataset3"},
  { program : "cbench-consumer-tiff2bw", value: "--dataset_uoa=image-tiff-0004", name: "dataset4"},
  { program : "cbench-consumer-tiff2bw", value: "--dataset_uoa=image-tiff-0005", name: "dataset5"},
  
  { program : "cbench-consumer-tiff2dither", value: "--dataset_uoa=image-tiff-0001-bw", name: "dataset1"},
  { program : "cbench-consumer-tiff2dither", value: "--dataset_uoa=image-tiff-0002-bw", name: "dataset2"},
  { program : "cbench-consumer-tiff2dither", value: "--dataset_uoa=image-tiff-0003-bw", name: "dataset3"},
  { program : "cbench-consumer-tiff2dither", value: "--dataset_uoa=image-tiff-0004-bw", name: "dataset4"},
  { program : "cbench-consumer-tiff2dither", value: "--dataset_uoa=image-tiff-0005-bw", name: "dataset5"},

  { program : "cbench-consumer-tiff2median", value: "--dataset_uoa=image-tiff-0001-bw", name: "dataset1"},
  { program : "cbench-consumer-tiff2median", value: "--dataset_uoa=image-tiff-0002-bw", name: "dataset2"},
  { program : "cbench-consumer-tiff2median", value: "--dataset_uoa=image-tiff-0003-bw", name: "dataset3"},
  { program : "cbench-consumer-tiff2median", value: "--dataset_uoa=image-tiff-0004-bw", name: "dataset4"},
  { program : "cbench-consumer-tiff2median", value: "--dataset_uoa=image-tiff-0005-bw", name: "dataset5"},

  { program : "cbench-consumer-tiff2rgba", value: "--dataset_uoa=image-tiff-0001", name: "dataset1"},
  { program : "cbench-consumer-tiff2rgba", value: "--dataset_uoa=image-tiff-0002", name: "dataset2"},
  { program : "cbench-consumer-tiff2rgba", value: "--dataset_uoa=image-tiff-0003", name: "dataset3"},
  { program : "cbench-consumer-tiff2rgba", value: "--dataset_uoa=image-tiff-0004", name: "dataset4"},
  { program : "cbench-consumer-tiff2rgba", value: "--dataset_uoa=image-tiff-0005", name: "dataset5"},
  
  { program : "cbench-network-dijkstra", value: "--dataset_uoa=cdataset-dijkstra-0001", name: "dataset1"},
  { program : "cbench-network-dijkstra", value: "--dataset_uoa=cdataset-dijkstra-0002", name: "dataset2"},
  { program : "cbench-network-dijkstra", value: "--dataset_uoa=cdataset-dijkstra-0003", name: "dataset3"},
  { program : "cbench-network-dijkstra", value: "--dataset_uoa=cdataset-dijkstra-0004", name: "dataset4"},
  { program : "cbench-network-dijkstra", value: "--dataset_uoa=cdataset-dijkstra-0005", name: "dataset5"},

  { program : "cbench-network-patricia", value: "--dataset_uoa=cdataset-patricia-0001", name: "dataset1"},
  { program : "cbench-network-patricia", value: "--dataset_uoa=cdataset-patricia-0002", name: "dataset2"},
  { program : "cbench-network-patricia", value: "--dataset_uoa=cdataset-patricia-0003", name: "dataset3"},
  { program : "cbench-network-patricia", value: "--dataset_uoa=cdataset-patricia-0004", name: "dataset4"},
  { program : "cbench-network-patricia", value: "--dataset_uoa=cdataset-patricia-0005", name: "dataset5"},


  { program : "cbench-office-stringsearch2", value: "--dataset_file=\"data.txt\" env.dataset_filename_1=data.txt --dataset_uoa=txt-0001", name: "dataset1"},
  { program : "cbench-office-stringsearch2", value: "--dataset_file=\"data.txt\" env.dataset_filename_1=data.txt --dataset_uoa=txt-0002", name: "dataset2"},
  { program : "cbench-office-stringsearch2", value: "--dataset_file=\"data.txt\" env.dataset_filename_1=data.txt --dataset_uoa=txt-0003", name: "dataset3"},
  { program : "cbench-office-stringsearch2", value: "--dataset_file=\"data.txt\" env.dataset_filename_1=data.txt --dataset_uoa=txt-0007", name: "dataset4"},
  { program : "cbench-office-stringsearch2", value: "--dataset_file=\"data.txt\" env.dataset_filename_1=data.txt --dataset_uoa=txt-0005", name: "dataset5"},

  { program : "cbench-security-rijndael", value: "--dataset_uoa=enc-0001", name: "dataset1", input: "decode"},
  { program : "cbench-security-rijndael", value: "--dataset_uoa=enc-0002", name: "dataset2", input: "decode"},
  { program : "cbench-security-rijndael", value: "--dataset_uoa=enc-0003", name: "dataset3", input: "decode"},
  { program : "cbench-security-rijndael", value: "--dataset_uoa=enc-0004", name: "dataset4", input: "decode"},
  { program : "cbench-security-rijndael", value: "--dataset_uoa=enc-0005", name: "dataset5", input: "decode"},

  { program : "cbench-security-rijndael", value: "--dataset_uoa=enc-0001", name: "dataset1", input: "encode"},
  { program : "cbench-security-rijndael", value: "--dataset_uoa=enc-0002", name: "dataset2", input: "encode"},
  { program : "cbench-security-rijndael", value: "--dataset_uoa=enc-0003", name: "dataset3", input: "encode"},
  { program : "cbench-security-rijndael", value: "--dataset_uoa=enc-0004", name: "dataset4", input: "encode"},
  { program : "cbench-security-rijndael", value: "--dataset_uoa=enc-0005", name: "dataset5", input: "encode"},

  { program : "cbench-security-sha", value: "--dataset_uoa=adpcm-0001", name: "dataset1"},
  { program : "cbench-security-sha", value: "--dataset_uoa=adpcm-0002", name: "dataset2"},
  { program : "cbench-security-sha", value: "--dataset_uoa=adpcm-0003", name: "dataset3"},
  { program : "cbench-security-sha", value: "--dataset_uoa=adpcm-0007", name: "dataset4"},
  { program : "cbench-security-sha", value: "--dataset_uoa=adpcm-0005", name: "dataset5"},

  { program : "cbench-telecom-adpcm-c", value: "--dataset_uoa=pcm-0001", name: "dataset1"},
  { program : "cbench-telecom-adpcm-c", value: "--dataset_uoa=pcm-0002", name: "dataset2"},
  { program : "cbench-telecom-adpcm-c", value: "--dataset_uoa=pcm-0003", name: "dataset3"},
  { program : "cbench-telecom-adpcm-c", value: "--dataset_uoa=pcm-0004", name: "dataset4"},
  { program : "cbench-telecom-adpcm-c", value: "--dataset_uoa=pcm-0005", name: "dataset5"},

  { program : "cbench-telecom-adpcm-d", value: "--dataset_uoa=adpcm-0001", name: "dataset1"},
  { program : "cbench-telecom-adpcm-d", value: "--dataset_uoa=adpcm-0002", name: "dataset2"},
  { program : "cbench-telecom-adpcm-d", value: "--dataset_uoa=adpcm-0003", name: "dataset3"},
  { program : "cbench-telecom-adpcm-d", value: "--dataset_uoa=adpcm-0004", name: "dataset4"},
  { program : "cbench-telecom-adpcm-d", value: "--dataset_uoa=adpcm-0005", name: "dataset5"},

  { program : "cbench-telecom-crc32", value: "--dataset_uoa=adpcm-0001", name: "dataset1"},
  { program : "cbench-telecom-crc32", value: "--dataset_uoa=adpcm-0002", name: "dataset2"},
  { program : "cbench-telecom-crc32", value: "--dataset_uoa=adpcm-0003", name: "dataset3"},
  { program : "cbench-telecom-crc32", value: "--dataset_uoa=adpcm-0004", name: "dataset4"},
  { program : "cbench-telecom-crc32", value: "--dataset_uoa=adpcm-0005", name: "dataset5"},

  { program : "cbench-telecom-gsm", value: "--dataset_uoa=au-0001", name: "dataset1"},
  { program : "cbench-telecom-gsm", value: "--dataset_uoa=au-0002", name: "dataset2"},
  { program : "cbench-telecom-gsm", value: "--dataset_uoa=au-0003", name: "dataset3"},
  { program : "cbench-telecom-gsm", value: "--dataset_uoa=au-0004", name: "dataset4"},
  { program : "cbench-telecom-gsm", value: "--dataset_uoa=au-0005", name: "dataset5"},

  { program : "polybench-cpu-3mm", compilation : true, value: "@polybench_dataset/polybench-cpu-3mm/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-3mm", compilation : true, value: "@polybench_dataset/polybench-cpu-3mm/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-3mm", compilation : true, value: "@polybench_dataset/polybench-cpu-3mm/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-3mm", compilation : true, value: "@polybench_dataset/polybench-cpu-3mm/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-trmm", compilation : true, value: "@polybench_dataset/polybench-cpu-trmm/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-trmm", compilation : true, value: "@polybench_dataset/polybench-cpu-trmm/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-trmm", compilation : true, value: "@polybench_dataset/polybench-cpu-trmm/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-trmm", compilation : true, value: "@polybench_dataset/polybench-cpu-trmm/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-lu", compilation : true, value: "@polybench_dataset/polybench-cpu-lu/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-lu", compilation : true, value: "@polybench_dataset/polybench-cpu-lu/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-lu", compilation : true, value: "@polybench_dataset/polybench-cpu-lu/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-lu", compilation : true, value: "@polybench_dataset/polybench-cpu-lu/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-doitgen", compilation : true, value: "@polybench_dataset/polybench-cpu-doitgen/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-doitgen", compilation : true, value: "@polybench_dataset/polybench-cpu-doitgen/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-doitgen", compilation : true, value: "@polybench_dataset/polybench-cpu-doitgen/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-doitgen", compilation : true, value: "@polybench_dataset/polybench-cpu-doitgen/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-jacobi-2d-imper", compilation : true, value: "@polybench_dataset/polybench-cpu-jacobi-2d-imper/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-jacobi-2d-imper", compilation : true, value: "@polybench_dataset/polybench-cpu-jacobi-2d-imper/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-jacobi-2d-imper", compilation : true, value: "@polybench_dataset/polybench-cpu-jacobi-2d-imper/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-jacobi-2d-imper", compilation : true, value: "@polybench_dataset/polybench-cpu-jacobi-2d-imper/dataset4.json", name: "dataset4"},
  
  { program : "polybench-cpu-fdtd-2d", compilation : true, value: "@polybench_dataset/polybench-cpu-fdtd-2d/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-fdtd-2d", compilation : true, value: "@polybench_dataset/polybench-cpu-fdtd-2d/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-fdtd-2d", compilation : true, value: "@polybench_dataset/polybench-cpu-fdtd-2d/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-fdtd-2d", compilation : true, value: "@polybench_dataset/polybench-cpu-fdtd-2d/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-symm", compilation : true, value: "@polybench_dataset/polybench-cpu-symm/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-symm", compilation : true, value: "@polybench_dataset/polybench-cpu-symm/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-symm", compilation : true, value: "@polybench_dataset/polybench-cpu-symm/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-symm", compilation : true, value: "@polybench_dataset/polybench-cpu-symm/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-atax", compilation : true, value: "@polybench_dataset/polybench-cpu-atax/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-atax", compilation : true, value: "@polybench_dataset/polybench-cpu-atax/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-atax", compilation : true, value: "@polybench_dataset/polybench-cpu-atax/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-atax", compilation : true, value: "@polybench_dataset/polybench-cpu-atax/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-bicg", compilation : true, value: "@polybench_dataset/polybench-cpu-bicg/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-bicg", compilation : true, value: "@polybench_dataset/polybench-cpu-bicg/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-bicg", compilation : true, value: "@polybench_dataset/polybench-cpu-bicg/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-bicg", compilation : true, value: "@polybench_dataset/polybench-cpu-bicg/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-adi", compilation : true, value: "@polybench_dataset/polybench-cpu-adi/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-adi", compilation : true, value: "@polybench_dataset/polybench-cpu-adi/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-adi", compilation : true, value: "@polybench_dataset/polybench-cpu-adi/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-adi", compilation : true, value: "@polybench_dataset/polybench-cpu-adi/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-gemm", compilation : true, value: "@polybench_dataset/polybench-cpu-gemm/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-gemm", compilation : true, value: "@polybench_dataset/polybench-cpu-gemm/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-gemm", compilation : true, value: "@polybench_dataset/polybench-cpu-gemm/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-gemm", compilation : true, value: "@polybench_dataset/polybench-cpu-gemm/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-jacobi-1d-imper", compilation : true, value: "@polybench_dataset/polybench-cpu-jacobi-1d-imper/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-jacobi-1d-imper", compilation : true, value: "@polybench_dataset/polybench-cpu-jacobi-1d-imper/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-jacobi-1d-imper", compilation : true, value: "@polybench_dataset/polybench-cpu-jacobi-1d-imper/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-jacobi-1d-imper", compilation : true, value: "@polybench_dataset/polybench-cpu-jacobi-1d-imper/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-gramschmidt", compilation : true, value: "@polybench_dataset/polybench-cpu-gramschmidt/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-gramschmidt", compilation : true, value: "@polybench_dataset/polybench-cpu-gramschmidt/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-gramschmidt", compilation : true, value: "@polybench_dataset/polybench-cpu-gramschmidt/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-gramschmidt", compilation : true, value: "@polybench_dataset/polybench-cpu-gramschmidt/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-fdtd-apml", compilation : true, value: "@polybench_dataset/polybench-cpu-fdtd-apml/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-fdtd-apml", compilation : true, value: "@polybench_dataset/polybench-cpu-fdtd-apml/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-fdtd-apml", compilation : true, value: "@polybench_dataset/polybench-cpu-fdtd-apml/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-fdtd-apml", compilation : true, value: "@polybench_dataset/polybench-cpu-fdtd-apml/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-ludcmp", compilation : true, value: "@polybench_dataset/polybench-cpu-ludcmp/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-ludcmp", compilation : true, value: "@polybench_dataset/polybench-cpu-ludcmp/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-ludcmp", compilation : true, value: "@polybench_dataset/polybench-cpu-ludcmp/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-ludcmp", compilation : true, value: "@polybench_dataset/polybench-cpu-ludcmp/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-trisolv", compilation : true, value: "@polybench_dataset/polybench-cpu-trisolv/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-trisolv", compilation : true, value: "@polybench_dataset/polybench-cpu-trisolv/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-trisolv", compilation : true, value: "@polybench_dataset/polybench-cpu-trisolv/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-trisolv", compilation : true, value: "@polybench_dataset/polybench-cpu-trisolv/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-gesummv", compilation : true, value: "@polybench_dataset/polybench-cpu-gesummv/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-gesummv", compilation : true, value: "@polybench_dataset/polybench-cpu-gesummv/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-gesummv", compilation : true, value: "@polybench_dataset/polybench-cpu-gesummv/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-gesummv", compilation : true, value: "@polybench_dataset/polybench-cpu-gesummv/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-mvt", compilation : true, value: "@polybench_dataset/polybench-cpu-mvt/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-mvt", compilation : true, value: "@polybench_dataset/polybench-cpu-mvt/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-mvt", compilation : true, value: "@polybench_dataset/polybench-cpu-mvt/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-mvt", compilation : true, value: "@polybench_dataset/polybench-cpu-mvt/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-syr2k", compilation : true, value: "@polybench_dataset/polybench-cpu-syr2k/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-syr2k", compilation : true, value: "@polybench_dataset/polybench-cpu-syr2k/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-syr2k", compilation : true, value: "@polybench_dataset/polybench-cpu-syr2k/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-syr2k", compilation : true, value: "@polybench_dataset/polybench-cpu-syr2k/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-cholesky", compilation : true, value: "@polybench_dataset/polybench-cpu-cholesky/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-cholesky", compilation : true, value: "@polybench_dataset/polybench-cpu-cholesky/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-cholesky", compilation : true, value: "@polybench_dataset/polybench-cpu-cholesky/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-cholesky", compilation : true, value: "@polybench_dataset/polybench-cpu-cholesky/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-dynprog", compilation : true, value: "@polybench_dataset/polybench-cpu-dynprog/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-dynprog", compilation : true, value: "@polybench_dataset/polybench-cpu-dynprog/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-dynprog", compilation : true, value: "@polybench_dataset/polybench-cpu-dynprog/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-dynprog", compilation : true, value: "@polybench_dataset/polybench-cpu-dynprog/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-medley-reg-detect", compilation : true, value: "@polybench_dataset/polybench-cpu-medley-reg-detect/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-medley-reg-detect", compilation : true, value: "@polybench_dataset/polybench-cpu-medley-reg-detect/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-medley-reg-detect", compilation : true, value: "@polybench_dataset/polybench-cpu-medley-reg-detect/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-medley-reg-detect", compilation : true, value: "@polybench_dataset/polybench-cpu-medley-reg-detect/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-medley-floyd-warshall", compilation : true, value: "@polybench_dataset/polybench-cpu-medley-floyd-warshall/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-medley-floyd-warshall", compilation : true, value: "@polybench_dataset/polybench-cpu-medley-floyd-warshall/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-medley-floyd-warshall", compilation : true, value: "@polybench_dataset/polybench-cpu-medley-floyd-warshall/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-medley-floyd-warshall", compilation : true, value: "@polybench_dataset/polybench-cpu-medley-floyd-warshall/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-syrk", compilation : true, value: "@polybench_dataset/polybench-cpu-syrk/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-syrk", compilation : true, value: "@polybench_dataset/polybench-cpu-syrk/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-syrk", compilation : true, value: "@polybench_dataset/polybench-cpu-syrk/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-syrk", compilation : true, value: "@polybench_dataset/polybench-cpu-syrk/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-2mm", compilation : true, value: "@polybench_dataset/polybench-cpu-2mm/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-2mm", compilation : true, value: "@polybench_dataset/polybench-cpu-2mm/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-2mm", compilation : true, value: "@polybench_dataset/polybench-cpu-2mm/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-2mm", compilation : true, value: "@polybench_dataset/polybench-cpu-2mm/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-seidel-2d", compilation : true, value: "@polybench_dataset/polybench-cpu-seidel-2d/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-seidel-2d", compilation : true, value: "@polybench_dataset/polybench-cpu-seidel-2d/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-seidel-2d", compilation : true, value: "@polybench_dataset/polybench-cpu-seidel-2d/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-seidel-2d", compilation : true, value: "@polybench_dataset/polybench-cpu-seidel-2d/dataset4.json", name: "dataset4"},

  { program : "polybench-cpu-gemver", compilation : true, value: "@polybench_dataset/polybench-cpu-gemver/dataset1.json", name: "dataset1"},
  { program : "polybench-cpu-gemver", compilation : true, value: "@polybench_dataset/polybench-cpu-gemver/dataset2.json", name: "dataset2"},
  { program : "polybench-cpu-gemver", compilation : true, value: "@polybench_dataset/polybench-cpu-gemver/dataset3.json", name: "dataset3"},
  { program : "polybench-cpu-gemver", compilation : true, value: "@polybench_dataset/polybench-cpu-gemver/dataset4.json", name: "dataset4"},

  { program : "bitbench-drop3", name: "dataset1"},
  { program : "bitbench-five11", name: "dataset1"},
  { program : "bitbench-uudecode", name: "dataset1"},
  { program : "bitbench-uuencode", name: "dataset1"},
  { program : "coyote-alma", name: "dataset1"},
  { program : "coyote-huff", name: "dataset1"},
  { program : "coyote-lp", name: "dataset1"},
  { program : "dhrystone-dry", name: "dataset1"},
  { program : "dhrystone-fldry", name: "dataset1"},
  { program : "doe_proxyapps_miniamr", name: "dataset1"},
  { program : "doe_proxyapps_minigmg", name: "dataset1"},
  { program : "doe_proxyapps_pathfinder", name: "dataset1"},
  { program : "doe_proxyapps_rsbench", name: "dataset1"},
  { program : "doe_proxyapps_simple_moc", name: "dataset1"},
  { program : "doe_proxyapps_xsbench", name: "dataset1"},
  { program : "fhourstones", name: "dataset1"},
  { program : "freebench-analyzer", name: "dataset1"},
  { program : "freebench-distray", name: "dataset1"},
  { program : "freebench-fourinarow", name: "dataset1"},
  { program : "freebench-mason", name: "dataset1"},
  { program : "freebench-neural", name: "dataset1"},
  { program : "freebench-pcompress2", name: "dataset1"},
  { program : "freebench-pifft", name: "dataset1"},
  { program : "game-fannkuch", name: "dataset1"},
  { program : "game-n-body", name: "dataset1"},
  { program : "game-nsieve-bits", name: "dataset1"},
  { program : "game-partialsums", name: "dataset1"},
  { program : "game-puzzle", name: "dataset1"},
  { program : "game-recursive", name: "dataset1"},
  { program : "game-spectral-norm", name: "dataset1"},
  { program: "asci_purple", name : "dataset1"},
  { program: "asc_sequoia_amgmk", name : "dataset1"},
  { program: "asc_sequoia_crystalmk", name : "dataset1"},
  { program: "asc_sequoia_irsmk", name : "dataset1"},
  { program: "fhourstones", name : "dataset1"},
  { program: "fhourstones_31", name : "dataset1"},
  { program: "linpack", name : "dataset1"},
  { program: "llubenchmark", name : "dataset1"},
  { program: "mafft", name : "dataset1"},
  { program: "mallocbench-cfrac", name : "dataset1"},
  { program: "mccat-main", name : "dataset1"},
  { program: "mccat-bintr", name : "dataset1"},
  { program: "mccat-bisect", name : "dataset1"},
  { program: "mccat-eks", name : "dataset1"},
  { program: "mccat-qbsort", name : "dataset1"},
  { program: "mccat-iotest", name : "dataset1"},
  { program: "mccat-vor", name : "dataset1"},
  { program: "mccat-testtrie", name : "dataset1"},
  { program: "mccat-trie", name : "dataset1"},
  { program: "mcgill-chomp", name : "dataset1"},
  { program: "mcgill-queens", name : "dataset1"},
  { program: "mcgill-exptree", name : "dataset1"},
  { program: "mcgill-misr", name : "dataset1"},
  { program: "mediabench-g721-encode", name : "dataset1"},
  { program: "mediabench-adpcm-rawcaudio", name : "dataset1"},
  { program: "mediabench-gsm-toast", name : "dataset1"},
  { program: "mediabench-adpcm-rawdaudio", name : "dataset1"},
  { program: "mediabench-mpeg2-dec", name : "dataset1"},
  { program: "misc-oourafft", name : "dataset1"},
  { program: "misc-flops-6", name : "dataset1"},
  { program: "misc-mandel-2", name : "dataset1"},
  { program: "misc-evalloop", name : "dataset1"},
  { program: "misc-salsa20", name : "dataset1"},
  { program: "misc-fp-convert", name : "dataset1"},
  { program: "misc-whetstone", name : "dataset1"},
  { program: "misc-dt", name : "dataset1"},
  { program: "misc-flops-2", name : "dataset1"},
  { program: "misc-perlin", name : "dataset1"},
  { program: "misc-flops-3", name : "dataset1"},
  { program: "misc-himenobmtxpa", name : "dataset1"},
  { program: "misc-flops-1", name : "dataset1"},
  { program: "misc-flops", name : "dataset1"},
  { program: "misc-reed-solomon", name : "dataset1"},
  { program: "misc-mandel", name : "dataset1"},
  { program: "misc-flops-7", name : "dataset1"},
  { program: "misc-flops-4", name : "dataset1"},
  { program: "misc-matmul_f64_4x4", name : "dataset1"},
  { program: "misc-pi", name : "dataset1"},
  { program: "misc-fbench", name : "dataset1"},
  { program: "misc-flops-8", name : "dataset1"},
  { program: "misc-revert-bits", name : "dataset1"},
  { program: "misc-ffbench", name : "dataset1"},
  { program: "misc-lowercase", name : "dataset1"},
  { program: "misc-flops-5", name : "dataset1"},
  { program: "misc-richards", name : "dataset1"},
]

const inputs = [
  { program : "cbench-automotive-susan", value: "--cmd_key=edges", name: "edges"},
  { program : "cbench-automotive-susan", value: "--cmd_key=corners", name : "corners"},
  { program : "cbench-automotive-susan", value: "--cmd_key=smoothing", name : "smoothing"},
  { program : "cbench-bzip2", value: "--cmd_key=decode", name : "decode"},
  { program : "cbench-bzip2", value: "--cmd_key=encode", name : "encode"},
  { program : "cbench-security-rijndael", value: "--cmd_key=encode", name : "encode"},
  { program : "cbench-security-rijndael", value: "--cmd_key=decode", name : "decode"}
]


const optimizations = [
  { reference_name : "O0" , value : "-O0" },
]

function get_directory_logs(){
  return process.env.directory_log ? process.env.directory_log : `${__dirname}/logs`
}

function get_pin_path(){
  return '/home/alan/pin-2.10-45467-gcc.3.4.6-ia32_intel64-linux/pin';
}

function get_mica_so(){
  return '/home/alan/pin-2.10-45467-gcc.3.4.6-ia32_intel64-linux/source/tools/mica_v0.40/mica.so'
}

function log(program, optimization, input, dataset, directory_base){
  console.log(`Extracting MICA features from program ${program} with:`)
  if (input && input.name) {
    console.log(`Input name: ${input.name}`)
  }
  if (dataset && dataset.value){
    console.log(`Dataset: ${dataset.name} / ${dataset.value}`)
  }
  console.log(`With optimization ${optimization.reference_name} for ${total_execution} times\n`);
}

async function run_program_with_optimization(program, optimization, input, dataset, directory_base){
  log(program, optimization, input, dataset, directory_base);

  let directory = directory_base.concat(`/${optimization.reference_name}`);
  await exec(`mkdir ${directory}`);
  await exec(`cp mica.conf itypes_default.spec ${directory}`);

  const result_compilation = await exec(`ck compile program:${program} ${dataset && dataset.compilation ? dataset.value : ""} --flags="${optimization.value}" --compiler_tags=milepost`, { maxBuffer : maxBuffer});
  fs.writeFileSync(directory.concat('/compilation.txt'), result_compilation.stdout);
  const { stdout } = await exec(`ck run program:${program} ${input ? input.value : ""} ${dataset && dataset.value && !dataset.compilation ? dataset.value : ""} ${skip_calibration ? "--skip_calibration" : ""} --skip_output_validation`, { maxBuffer : maxBuffer});
  const paramater = stdout.match('(./a.out)(.*?)>+')[2];
  await exec(`cd ${directory} && ${get_pin_path()} -injection child -t ${get_mica_so()} -- \`ck find program:${program}\`/tmp/a.out ${paramater}`, { maxBuffer : maxBuffer });
}

async function run_program(program){
  await exec(`mkdir ${get_directory_logs().concat(`/${program}`)}`);
  let program_inputs = inputs.filter(e => e.program === program);
  if (program_inputs.length) {
    for (let input of program_inputs) {
      let directory_input = get_directory_logs().concat(`/${program}`);
      if (input.name) {
        directory_input = get_directory_logs().concat(`/${program}/${input.name}`);
        await exec(`mkdir ${directory_input}`);
      }
      
      const program_datasets = datasets.filter(e => e.program === program && e.input === input.name);
      for (const dataset of program_datasets){
        let directory_dataset = directory_input.concat(`/${dataset.name}`);
        await exec(`mkdir ${directory_dataset}`);
        for (let optimization of optimizations){
          await run_program_with_optimization(program, optimization, input, dataset, directory_dataset);
        }
      }

    }  
  } else {
    let directory_base = get_directory_logs().concat(`/${program}`);

    const program_datasets = datasets.filter(e => e.program === program);
    for (const dataset of program_datasets){
      let directory_dataset = directory_base.concat(`/${dataset.name}`);
      await exec(`mkdir ${directory_dataset}`);
      for (let optimization of optimizations){
        await run_program_with_optimization(program, optimization, undefined, dataset, directory_dataset);
      }
     }
  }

}

async function run(){
  if (fs.existsSync(get_directory_logs())) {
    console.log('Log directory already exists, please remove before run this module');
    return;
  }

  await exec(`mkdir ${get_directory_logs()}`);
  for (let program of programs) {
    await run_program(program);
  }
}

run();


